# Path to adapt by user
output_dir: 
    junction_annotation: root_dir/als/junction_annotation/
    splicing_preds: root_dir/als/splicing_predictions/
    outliers: root_dir/als/outlier_ground_truth/
    vcf_annotation: root_dir/als/vcf_annotation/
    benchmark: root_dir/als/benchmark/
    proteomics: root_dir/als/proteomics/

genome: 'hg38'
fasta: root_dir/genomes/human/hg38/gencode.v38/GRCh38.primary_assembly.genome.fa
gtf: root_dir/genomes/human/hg38/gencode.v38/gencode.v38.annotation.gtf

gene_count: root_dir/als/download/transcriptomics/4_matrix/AnswerALS-290-T-v1-release5_rna-counts-matrix.csv
        
vcf: root_dir/vcf_processing/ALS/vcf_normalized/{vcf_id}.vcf.gz

DROP:
    outlier_ground_truth_all: root_dir/als/DROP_output/processed_results/aberrant_splicing/results/v38/fraser/
    tissue_map: root_dir/absplice/data/results/als/tissue_map_DROP.csv
    sample_annotation_pure: root_dir/als/analysis/sample_annotation_drop.tsv
    sample_annotation: root_dir/absplice/data/results/als/junction_annotation/sample_annotation_drop.tsv
    version: 'v38'
    analysis_name: 'release5'
    splicemap:
        working_dir: root_dir/als/DROP_output/processed_data/aberrant_splicing/datasets/
    outlier:
        splicing:
            working_dir: root_dir/als/DROP_output/processed_results/aberrant_splicing/datasets/
        expression:
            working_dir: root_dir/als/DROP_output/processed_results/aberrant_expression/ 
            
proteomics:
    full_results: root_dir/als/analysis/proteomics/results_all.tsv
    full_results_annotated: PROTRIDER_results_annotated.csv
    enrichment: proteomics_enrichment.csv
    true_preds: proteomics_true_preds.csv
    motor_neuron_splicemap:
        enrichment: proteomics_enrichment_motor_neuron_splicemap.csv
        true_preds: proteomics_true_preds_motor_neuron_splicemap.csv
        
als_known_genes:
    gtex_splicemaps: als_known_genes/gtex_splicmaps/enrichment_known_als_genes.csv
    dataset_splicemap: als_known_genes/dataset_splicemap/enrichment_known_als_genes.csv
          
          
# Not to change by user
filtering_params:
    vcf:
        format_fields: ['GT','GQ','DP','AD']
        remove_chr: False
        min_GQ: 99
        min_DP_ALT: 10
        filter_long_indels: 10
    count_table:
        update_samples: True
        key_assay: 'RNA_ID'
        value_assay: 'VCF_ID'
        subset_chroms: False
        infer_strand: False
    splicemap:
        use_faster: True
        percentile: 95
        percentile_min_read: 1
        median_cutoff: 1
    outliers:
        padjustGene_cutoff: 0.1
        padjust_junction_cutoff: 0.05
        totalCounts_cutoff: 20
        delta_psi_cutoff: 0.3
        outlier_type: 'psi5__psi3__theta'
        num_junction_outliers_per_samples: 15
    outliers_expression:
        padjust: 0.05
    absplice:
        median_n_cutoff: 10
        tpm_cutoff: 1
        count_cat_cutoff: 20
        
  
tissue_dataset: 'motor_neuron'
tissues_cat: 
    - motor_neuron

spliceai:
    lookup_only: False
   
method: 'kn'
event_filter: 'median_cutoff'
gtex_version: 'gtex_v8'

tissue_subsets_for_pred:
    - Brain
gtex_tissues:
    - Brain_Amygdala
    - Brain_Anterior_cingulate_cortex_BA24
    - Brain_Caudate_basal_ganglia
    - Brain_Cerebellar_Hemisphere
    - Brain_Cerebellum
    - Brain_Cortex
    - Brain_Frontal_Cortex_BA9
    - Brain_Hippocampus
    - Brain_Hypothalamus
    - Brain_Nucleus_accumbens_basal_ganglia
    - Brain_Putamen_basal_ganglia
    - Brain_Spinal_cord_cervical_c_1
    - Brain_Substantia_nigra

chroms:
  - 'chr1'
  - 'chr2'
  - 'chr3'
  - 'chr4'
  - 'chr5'
  - 'chr6'
  - 'chr7'
  - 'chr8'
  - 'chr9'
  - 'chr10'
  - 'chr11'
  - 'chr12'
  - 'chr13'
  - 'chr14'
  - 'chr15'
  - 'chr16'
  - 'chr17'
  - 'chr18'
  - 'chr19'
  - 'chr20'
  - 'chr21'  
  - 'chr22'
  - 'chrX'