# Path to adapt by user
output_dir: 
    junction_annotation: root_dir/mito/junction_annotation/
    splicing_preds: root_dir/mito/splicing_predictions/
    outliers: root_dir/mito/outlier_ground_truth/
    vcf_annotation: root_dir/mito/vcf_annotation/
    benchmark: root_dir/mito/benchmark/

genome: 'hg19'
fasta: root_dir/genomes/Gencode/Gencode_human/release_34/GRCh37_mapping/GRCh37.primary_assembly.genome.fa
gtf: root_dir/genomes/Gencode/Gencode_human/release_34/GRCh37_mapping/gencode.v34lift37.annotation.gtf.gz

gene_tpm_dataset: root_dir/hg19/gene_expression_tpm/Prokisch_Fibroblasts_tpm.csv

vcf: root_dir/vcf_processing/mito/per_chrom/{vcf_id}.vcf.gz

DROP:
    outlier_ground_truth_all: root_dir/mito/processed_results/aberrant_splicing/results/v29/fraser/
    tissue_map: root_dir/mito/tissue_map_DROP.csv
    sample_annotation: root_dir/mito/sample_anno_prokisch_updated_fib_all_new_results.tsv
    version: 'v29'
    splicemap:
        working_dir: root_dir/mito/processed_data/aberrant_splicing/datasets/
    outlier:
        splicing:
            working_dir: root_dir/mito/processed_results/aberrant_splicing/datasets/
        expression:
            working_dir: root_dir/mito/processed_results/aberrant_expression/
            
# Not to change by user
filtering_params:
    vcf:
        format_fields: ['GT','GQ','DP','AD']
        remove_chr: False
        min_GQ: 99
        min_DP_ALT: 10
        filter_long_indels: 10
    count_table:
        update_samples: True
        key_assay: 'RNA_ID'
        value_assay: 'GENOME_ID'
        subset_chroms: False
        infer_strand: False
    splicemap:
        use_faster: True
        percentile: 95
        percentile_min_read: 1
        median_cutoff: 1
    outliers:
        padjustGene_cutoff: 0.1
        padjust_junction_cutoff: 0.05
        totalCounts_cutoff: 20
        delta_psi_cutoff: 0.3
        outlier_type: 'psi5__psi3__theta'
        num_junction_outliers_per_samples: 15
    absplice:
        median_n_cutoff: 10
        tpm_cutoff: 1
        count_cat_cutoff: 20
        
spliceai:
    lookup_only: False
   
method: 'kn'
event_filter: 'median_cutoff'
gtex_version: 'gtex_v7'

tissues_cat: 
    - Prokisch_Fibroblasts
    
tissue_dataset: 'Prokisch_Fibroblasts'

tissue_subsets_for_pred:
    - Cells_Cultured_fibroblasts

gtex_tissues:
    - Cells_Cultured_fibroblasts
    
sampleIDs:
    - 33254G
    - 33281G
    - 35791G
    - 53890G
    - 62524G
    - 62631G
    - 63045G
    - 66744G
    - 68540G
    - 68544G
    - 68546G
    - 68547G
    - 68558G
    - 69340G
    - 71724G
    - 73388G
    - 73804G
    - 93741G
    - 94626G
    - EXT_ITA_PI_SANT01_IDX
    
chroms:
  - 'chr1'
  - 'chr2'
  - 'chr3'
  - 'chr4'
  - 'chr5'
  - 'chr6'
  - 'chr7'
  - 'chr8'
  - 'chr9'
  - 'chr10'
  - 'chr11'
  - 'chr12'
  - 'chr13'
  - 'chr14'
  - 'chr15'
  - 'chr16'
  - 'chr17'
  - 'chr18'
  - 'chr19'
  - 'chr20'
  - 'chr21'  
  - 'chr22'
  - 'chrX'

    



